<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <parent>
      <artifactId>taxi-lang-server</artifactId>
      <groupId>org.taxilang</groupId>
      <version>1.70.0</version>
   </parent>
   <modelVersion>4.0.0</modelVersion>

   <properties>
      <!-- We're depending on transpilation code here,
      so this doesn't need to stay always up-to-date, but avoid using a
      snapshot dependency -->
      <orbital.version>0.36.0-M11</orbital.version>
   </properties>

   <!--
If you're reading this trying to manually build the vscode plugin,
make sure you run maven with the shade profile enabled.  (-P shade)
That is used to create a fat jar.  Enable by default in ci/cd,
disabled by default locally
-->

   <artifactId>taxi-lang-server-standalone</artifactId>

   <dependencies>
      <!--
      This isn't great, I know.
      We have a taxi dependency (albeit, very fringe)
      The schema server project has all the code for transpilation of in-project sources.
      Without this, taxi projects which have OAS / Avro dependencies within them
      can't load / compile.

      In the future, I guess we'll need to migrate this code, possibly.

      However, this does introduce a challenge where the current version of Taxi
      depends on a version of Orbital, which - by definition - must depend on
      an OLDER version of Taxi. (It can't depend on this version, as it's not
      released yet!)

      We need to be careful with exclusions here, so that things like the compiler
      aren't pulled in transitively from schema-server, so that the language server
      is using the "current" version of the Taxi build chain.

      However, some things - like language adaptors from Taxi - will always have to stay
      a release behind inside the language server (LangServer (vT) -> Orbital -> TaxiLangAdaptors (vT-1) )

      VERY IMPORTANT: This dependency intentionally DOES NOT live in general-purpose
      language server jars, only in the standalone launcher jar.
      This is so that Orbital dependencies on language server don't end up pulling
      in these Orbital dependencies, which would create circular transitive dependencies
      worse than Christopher Nolan's "Inception".
      -->
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-server-core</artifactId>
         <version>${orbital.version}</version>
         <exclusions>
            <exclusion>
               <groupId>org.taxilang</groupId>
               <artifactId>compiler</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.taxilang</groupId>
               <artifactId>core-types</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.taxilang</groupId>
               <artifactId>core-types</artifactId>
            </exclusion>
            <!-- try to keep the surface area of Orbital imports
            very small - only what is needed for transpiling sources.
             However, tread lightly, as if we remove something that is actually needed,
             the language server will fail silently at runtime.
             -->
            <exclusion>
               <groupId>com.orbitalhq</groupId>
               <artifactId>vyne-spring</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.jooq.pro</groupId>
               <artifactId>jooq</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.jooq</groupId>
               <artifactId>jooq</artifactId>
            </exclusion>
            <exclusion>
               <groupId>io.confluent</groupId>
               <artifactId>kafka-avro-serializer</artifactId>
            </exclusion>
         </exclusions>
      </dependency>
      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>taxi-lang-service</artifactId>
         <version>${project.version}</version>
      </dependency>
   </dependencies>

   <build>
      <finalName>taxi-lang-server</finalName>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
               <execution>
                  <id>copy-dependencies</id>
                  <phase>prepare-package</phase>
                  <goals>
                     <goal>copy-dependencies</goal>
                  </goals>
                  <configuration>
                     <outputDirectory>${project.build.directory}/dependency</outputDirectory>
                  </configuration>
               </execution>
            </executions>
         </plugin>
         <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>3.5.0</version>
            <configuration>
               <descriptorRefs>
                  <descriptorRef>jar-with-dependencies</descriptorRef>
               </descriptorRefs>
               <archive>
                  <manifest>
                     <mainClass>lang.taxi.lsp.Launcher</mainClass>
                  </manifest>
               </archive>
            </configuration>
            <executions>
               <execution>
                  <id>make-assembly</id> <!-- this is used for inheritance merges -->
                  <phase>package</phase> <!-- bind to the packaging phase -->
                  <goals>
                     <goal>single</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
      </plugins>
   </build>

   <repositories>
      <!-- for orbital snapshots -->
      <repository>
         <id>orbital-snapshots</id>
         <url>https://repo.orbitalhq.com/snapshot</url>
         <snapshots>
            <enabled>true</enabled>
         </snapshots>
      </repository>
      <repository>
         <id>vyne</id>
         <url>https://repo.orbitalhq.com/release</url>
         <snapshots>
            <enabled>false</enabled>
         </snapshots>
      </repository>
   </repositories>
</project>
