// This is a file for defining credentials when connecting to services.
// You can use environment variables for actual values, to avoid committing them
// to version control.
// Read more about definining auth tokens at
// https://orbitalhq.com/docs/describing-data-sources/authentication-to-services
//
// Changes to this file are live-reloaded, if your environment supports it. (Hint: k8s generally doesn't)

// Root element, required.
authenticationTokens {

   // The fully qualified name of a service, as defined in a taxi schema.
   // Should be surrounded in quotes.
//   "com.foo.TestService" {
//      type: Basic
//      username: jimmy
//      password: password
//   }

}
