// This is a connections.conf file, where you define
// connections to data sources such as databases, kafka topics, AWS instances, etc.
// Read more about how to configure connections.conf files at https://orbitalhq.com/docs/describing-data-sources/configuring-connections
// Changes to this file are live-reloaded, if your environment supports it. (Hint: k8s generally doesn't)

aws {

}
kafka {

}
jdbc {

}
mongo {

}
