// This is a config file for modifying the url of http services.
// Often you want the actual url to vary between environments.
// services.conf file lets you define dynamic urls.
// First, declare your services against a placeholder domain name (in this example, 'filmsApi'):
//
// service ReviewsApi {
//    @HttpOperation(method = "GET", url = "https://filmsApi/reviews")
//    operation getReviews(): FilmReview[]
//}
//
// Then, in this services.conf file, you can define where filmsApi is resolved against:
//
// services {
//   filmsApi {
//     url="http://localhost:8080"
//   }
// }
//
// When getReviews() is called, it will be resolved to http://localhost:8080/reviews
//
// Changes to this file are live-reloaded, if your environment supports it. (Hint: k8s generally doesn't)
//
// Read more about services.conf files at
// https://orbitalhq.com/docs/describing-data-sources/http#modifying-server-ur-ls

// Root element, required.
services {

}
