// This is a workspace definition file.
// Workspaces allow you to work on multiple projects within Orbital.
file {
   changeDetectionMethod=WATCH
   incrementVersionOnChange=false
   newProjectsPath="projects"
   pollFrequency=PT5S
   recompilationFrequencyMillis=PT3S
   projects=[
      {
         isEditable=true
         loader {
            packageType=Taxi
         }
         path="projects/{PROJECT_NAME}"
      }
   ]
}
git {
   checkoutRoot="projects"
   diskChangeDetectionMethod=WATCH
   diskPollFrequency=PT30S
   pollFrequency=PT30S
   repositories=[]
}
