{
   "type": "record",
   "name": "AddressBook",
   "taxi.dataType": "foo.AddressBook",
   "namespace": "simple",
   "fields": [
      {
         "name": "people",
         "type": {
            "type": "array",
            "items": {
               "type": "record",
               "name": "Person",
               "fields": [
                  {
                     "name": "name",
                     "type": "string",
                     // declaring a type name using a name property on an object
                     // Type is not declared, it is imported
                     "taxi.dataType": {
                        "name": "foo.PersonName"
                     }
                  },
                  {
                     "name": "id",
                     "type": "int",
                     // declaring a type using a pure string
                     // Type is not declared, it is imported
                     "taxi.dataType": "foo.PersonId"
                  },
                  {
                     "name": "email",
                     "type": "string",
                     // declaring a type usiong an object, and defining this type should be declared (vs imported)
                     "taxi.dataType": {
                        "name" : "foo.EmailAddress",
                        "create" : true
                     }
                  },
                  {
                     "name": "phones",
                     "type": {
                        "type": "array",
                        "items": {
                           "type": "record",
                           "name": "PhoneNumber",
                           "fields": [
                              {
                                 "name": "number",
                                 "type": "string"
                              },
                              {
                                 "name": "type",
                                 "type": {
                                    "type": "enum",
                                    "name": "PhoneType",
                                    "taxi.dataType": "foo.PhoneTypeEnum",
                                    "symbols": [
                                       "MOBILE",
                                       "HOME",
                                       "WORK"
                                    ]
                                 }
                              }
                           ]
                        }
                     }
                  },
                  {
                     "name": "last_updated",
                     "type": {
                        "type": "long",
                        "logicalType": "timestamp-micros"
                     }
                  }
               ]
            }
         }
      }
   ]
}
